/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminMomentsRouteImport } from './routes/admin.moments'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as ActivitySlugRouteImport } from './routes/activity.$slug'

const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMomentsRoute = AdminMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const ActivitySlugRoute = ActivitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ActivityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/join': typeof JoinRoute
  '/moments': typeof MomentsRoute
  '/activity/$slug': typeof ActivitySlugRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/join': typeof JoinRoute
  '/moments': typeof MomentsRoute
  '/activity/$slug': typeof ActivitySlugRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/join': typeof JoinRoute
  '/moments': typeof MomentsRoute
  '/activity/$slug': typeof ActivitySlugRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/moments': typeof AdminMomentsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/community'
    | '/join'
    | '/moments'
    | '/activity/$slug'
    | '/admin/activities'
    | '/admin/members'
    | '/admin/moments'
    | '/admin/schedules'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/community'
    | '/join'
    | '/moments'
    | '/activity/$slug'
    | '/admin/activities'
    | '/admin/members'
    | '/admin/moments'
    | '/admin/schedules'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/auth'
    | '/community'
    | '/join'
    | '/moments'
    | '/activity/$slug'
    | '/admin/activities'
    | '/admin/members'
    | '/admin/moments'
    | '/admin/schedules'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  JoinRoute: typeof JoinRoute
  MomentsRoute: typeof MomentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moments': {
      id: '/admin/moments'
      path: '/moments'
      fullPath: '/admin/moments'
      preLoaderRoute: typeof AdminMomentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/activity/$slug': {
      id: '/activity/$slug'
      path: '/$slug'
      fullPath: '/activity/$slug'
      preLoaderRoute: typeof ActivitySlugRouteImport
      parentRoute: typeof ActivityRoute
    }
  }
}

interface ActivityRouteChildren {
  ActivitySlugRoute: typeof ActivitySlugRoute
}

const ActivityRouteChildren: ActivityRouteChildren = {
  ActivitySlugRoute: ActivitySlugRoute,
}

const ActivityRouteWithChildren = ActivityRoute._addFileChildren(
  ActivityRouteChildren,
)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMomentsRoute: typeof AdminMomentsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMomentsRoute: AdminMomentsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  JoinRoute: JoinRoute,
  MomentsRoute: MomentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
